# Generated by Django 4.2.7 on 2026-01-15 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.FloatField(default=0.0, verbose_name='Вес в итоговой оценке')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Группа KPI',
                'verbose_name_plural': 'Группы KPI',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KpiIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название показателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('formula', models.TextField(blank=True, verbose_name='Формула расчета')),
                ('data_source', models.CharField(choices=[('api', 'Автоматический сбор (API)'), ('manual', 'Ручной ввод'), ('import', 'Импорт из систем')], default='manual', max_length=20)),
                ('max_value', models.FloatField(default=0.0, verbose_name='Максимальное значение (план)')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес показателя')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='kpi.kpigroup')),
            ],
            options={
                'verbose_name': 'Показатель KPI',
                'verbose_name_plural': 'Показатели KPI',
                'ordering': ['group__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KpiRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Период (ГГГГ-ММ)')),
                ('text', models.TextField(verbose_name='Текст рекомендации')),
                ('target_value', models.FloatField(default=0.0, verbose_name='Целевое значение')),
                ('deadline_period', models.CharField(blank=True, max_length=7, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpiindicator', verbose_name='Показатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекомендация KPI',
                'verbose_name_plural': 'Рекомендации KPI',
            },
        ),
        migrations.CreateModel(
            name='KpiValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Период (ГГГГ-ММ)')),
                ('actual_value', models.FloatField(default=0.0, verbose_name='Фактическое значение')),
                ('target_value', models.FloatField(default=0.0, verbose_name='Плановое значение')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='Подтверждающий документ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpiindicator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Значение KPI',
                'verbose_name_plural': 'Значения KPI',
                'unique_together': {('user', 'indicator', 'period')},
            },
        ),
    ]
