# Generated by Django 5.0.1 on 2026-03-22 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Неверный формат ORCID. Ожидается: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')], verbose_name='ORCID идентификатор'),
        ),
    ]
