# Generated by Django 5.0.1 on 2026-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_orcid_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpirecommendation',
            options={'ordering': ['priority', '-current_completion'], 'verbose_name': 'Рекомендация KPI', 'verbose_name_plural': 'Рекомендации KPI'},
        ),
        migrations.AddField(
            model_name='kpirecommendation',
            name='actual_value',
            field=models.FloatField(default=0.0, verbose_name='Фактическое значение'),
        ),
        migrations.AddField(
            model_name='kpirecommendation',
            name='current_completion',
            field=models.FloatField(default=0.0, verbose_name='Процент выполнения'),
        ),
        migrations.AddField(
            model_name='kpirecommendation',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='kpirecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
