# Generated by Django 5.0.1 on 2026-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_recommendation_improvements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpigroup',
            options={'ordering': ['role', 'order'], 'verbose_name': 'Группа KPI', 'verbose_name_plural': 'Группы KPI'},
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='max_points',
            field=models.FloatField(default=0.0, verbose_name='Максимум баллов по группе'),
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='min_threshold',
            field=models.FloatField(default=0.0, verbose_name='Минимальный порог (баллы)'),
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='role',
            field=models.CharField(choices=[('pps', 'ППС (преподаватель)'), ('rop', 'РОП (руководитель)')], default='pps', max_length=10, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='kpiindicator',
            name='max_points',
            field=models.FloatField(default=0.0, verbose_name='Максимум баллов'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pps', 'ППС (преподаватель)'), ('rop', 'РОП (руководитель)')], default='pps', max_length=10, verbose_name='Роль в системе KPI'),
        ),
    ]
