# Generated by Django 5.0.1 on 2026-03-25 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_add_avatar_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiValueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Изменено'), ('submitted', 'Отправлено на проверку'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('old_value', models.FloatField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.FloatField(blank=True, null=True, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('kpi_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kpi.kpivalue')),
            ],
            options={
                'verbose_name': 'Лог изменения KPI',
                'verbose_name_plural': 'Логи изменений KPI',
                'ordering': ['-created_at'],
            },
        ),
    ]
