# Generated by Django 5.0.1 on 2026-03-31 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_add_kpi_value_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='Период (ГГГГ-ММ)')),
                ('target_value', models.FloatField(verbose_name='Плановое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Индивидуальный план KPI',
                'verbose_name_plural': 'Индивидуальные планы KPI',
            },
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['user', 'period'], name='kpival_user_period_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['status'], name='kpival_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kpivalue',
            index=models.Index(fields=['period'], name='kpival_period_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='kpi.kpiindicator'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='set_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_targets', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kpitarget',
            unique_together={('user', 'indicator', 'period')},
        ),
    ]
