# Generated by Django 5.0.1 on 2026-04-19 18:12

import apps.kpi.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0011_add_kpi_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpivalue',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), apps.kpi.models.validate_evidence_file_size], verbose_name='Подтверждающий документ'),
        ),
        migrations.AlterField(
            model_name='kpivaluelog',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('updated', 'Изменено'), ('submitted', 'Отправлено на проверку'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('crossref_import', 'Импорт из Crossref')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submitted', 'KPI подан на проверку'), ('approved', 'KPI одобрен'), ('rejected', 'KPI отклонён'), ('crossref_import', 'Импорт публикаций из Crossref')], max_length=20),
        ),
    ]
